/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e66575b19703c50bc67b1a5
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";

// Custom Actions


// START IMPORT ACTIONS
import EstudiantesActions from "../redux/actions/EstudiantesActions";

// END IMPORT ACTIONS

/** APIs

* actionsEstudiantes.create
*	@description CRUD ACTION create
*
* actionsEstudiantes.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsEstudiantes.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/

class EstudiantesEdit extends Component {
  // Init estudiantes
  constructor(props) {
    super(props);
    this.state = {
      estudiantes: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsEstudiantes.loadEstudiantes(this.props.match.params.id);
    }
    
  }

  // Insert props estudiantes in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      estudiantes: props.estudiantes
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.estudiantes._id) {
      this.props.actionsEstudiantes.saveEstudiantes(this.state.estudiantes).then(data => {
        this.props.history.push("/estudianteses/");
      });
    } else {
      this.props.actionsEstudiantes.createEstudiantes(this.state.estudiantes).then(data => {
        this.props.history.push("/estudianteses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Estudiantes Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="apellido"
            label="Apellido"
            value={this.state.estudiantes.apellido || ""}
            onChange={Utils.handleChange.bind(this, "estudiantes")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="nombre"
            label="Nombre"
            value={this.state.estudiantes.nombre || ""}
            onChange={Utils.handleChange.bind(this, "estudiantes")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.estudiantes.nombre && this.state.estudiantes.nombre === ""
              ? { error: true }
              : {})}
          />
          

          {/* Footer */}
          <div className="footer-card">
            <Link to="/estudianteses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsEstudiantes: bindActionCreators(EstudiantesActions, dispatch),
  };
};

// Validate types
EstudiantesEdit.propTypes = { 
  actionsEstudiantes: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    estudiantes: state.EstudiantesEditReducer.estudiantes
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EstudiantesEdit);
